site:
  title: openDAQ
  start_page: opendaq::introduction.adoc
asciidoc:
  attributes:
    page-pagination: true
    tabs-sync-option: true
    gpp: g++
    docs-prefix: docs
    docs-website: https://{docs-prefix}.opendaq.com/
  extensions:
    - "@asciidoctor/tabs"
        
antora:
  extensions:
    - require: "@antora/lunr-extension" 
      index_latest_only: true
    - require: "@springio/antora-extensions/tabs-migration-extension"
    - require: 'antora-apidocs-extension'
      api_docs_generator:
        with:
          source: docs/Doxygen  # Must match your Doxyfile location
          output: doxygen
        doxygen:
          code_directory: core
          doxygen_path: /usr/bin/doxygen
          working_path: /tmp
          output_files_destination: docs/Antora/modules/reference
          output_files_build_dir: build
          attachment_dir: cdoc
          index_filename: index.html
          api_docs_link_text: "Reference"
          specialty_files:
            - file_name: docs/Doxygen/Doxyfile
              is_required: true
              is_common_capable: true
              common_file_path: docs/Doxygen/Doxyfile

content:
  sources:
  - url: .
    branches: HEAD
    start_paths: docs/Antora, docs/Antora-specs
ui:
  bundle:
    url: https://github.com/openDAQ/antora-ui-spring/releases/download/1.11-opendaq/ui-bundle.zip
    snapshot: true
