site:
  title: openDAQ
  start_page: opendaq::introduction.adoc
asciidoc:
  attributes:
    doxygen_source_folder: "../../../src"  # Relative path to source code
    page-pagination: true
    tabs-sync-option: true
    gpp: g++
    docs-prefix: docs
    docs-website: https://{docs-prefix}.opendaq.com/
  extensions:
    - "@asciidoctor/tabs"

antora:
  extensions:
    - require: "@antora/lunr-extension" 
      index_latest_only: true
    - require: "@springio/antora-extensions/tabs-migration-extension"
    - require: "./asam-antora-extensions/asam-antora_extension.js"
      options:
        doxygen:
          xmlDir: './build/doxygen/xml'  # Path to Doxygen XML output
          componentName: 'reference'     # Must match your antora.yml name
          module: 'reference'            # Must match your module directory
          version: 'dev'                 # Explicit version matching antora.yml
      doxygen: true

content:
  sources:
  - url: .
    branches: HEAD
    start_paths: docs/Antora, docs/Antora-specs
ui:
  bundle:
    url: https://github.com/openDAQ/antora-ui-spring/releases/download/1.11-opendaq/ui-bundle.zip
    snapshot: true
